"""add unique constrain ton user phone

Revision ID: 8460cc7f8752
Revises: 8678d03efb4e
Create Date: 2026-06-10 06:44:09.101825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8460cc7f8752'
down_revision: Union[str, Sequence[str], None] = '8678d03efb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_full_phone_number', 'users', ['phone_country_code', 'phone_country_number', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_full_phone_number', 'users', type_='unique')
    # ### end Alembic commands ###
