"""update post table

Revision ID: 8d3484654a2f
Revises: ee273106451e
Create Date: 2026-06-12 06:52:22.018784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d3484654a2f'
down_revision: Union[str, Sequence[str], None] = 'ee273106451e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('posts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('posts', 'created_ad')
    op.drop_column('posts', 'updated_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('updated_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('created_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
