"""create todos table

Revision ID: ac325f37f089
Revises: b3bb9652f771
Create Date: 2026-06-10 21:16:02.747361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac325f37f089'
down_revision: Union[str, Sequence[str], None] = 'b3bb9652f771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True, server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
