"""create todos table

Revision ID: aeac660429d5
Revises: ac325f37f089
Create Date: 2026-06-10 21:20:05.450136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeac660429d5'
down_revision: Union[str, Sequence[str], None] = 'ac325f37f089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill existing NULL rows before enforcing NOT NULL
    op.execute("UPDATE users SET is_locked = false WHERE is_locked IS NULL")
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.false(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
