"""atte field to user table

Revision ID: b3bb9652f771
Revises: 6b311f4ded16
Create Date: 2026-06-10 19:29:52.156781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3bb9652f771'
down_revision: Union[str, Sequence[str], None] = '6b311f4ded16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_locked', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
