"""create post table

Revision ID: ee273106451e
Revises: 1e941a89591e
Create Date: 2026-06-12 06:35:16.166824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee273106451e'
down_revision: Union[str, Sequence[str], None] = '1e941a89591e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=400), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('create_by', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_ad', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_ad', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
